source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets

gem "trailblazer"
gem "trailblazer-future", path: '../../../trailblazer-future'
gem "trailblazer-rails"


group :test do
  gem "minitest-rails-capybara"
end

gem "trailblazer-cells"
gem "cells-rails"
gem "cells-erb"

gem "minitest-line"

gem "reform-rails"
